const MOBILE_CANT_UPDATE = require('./MOBILE_CANT_UPDATE');
const INPUT_FORMAT_ERROR = require('./INPUT_FORMAT_ERROR');
const STUDENT_DOES_NOT_EXIST = require('./STUDENT_DOES_NOT_EXIST');
const STUDENT_ALREADY_EXIST = require('./STUDENT_ALREADY_EXIST');
const UNAUTHORIZED_ACCESS = require('./UNAUTHORIZED_ACCESS');
const DATA_BASE_ERROR = require('./DATA_BASE_ERROR');
const SCHEMA_VALIDATION_ERROR=require('./SCHEMA_VALIDATION_ERROR');


module.exports = {
   INPUT_FORMAT_ERROR,
  STUDENT_DOES_NOT_EXIST,
  STUDENT_ALREADY_EXIST,
  UNAUTHORIZED_ACCESS,
  DATA_BASE_ERROR,
  MOBILE_CANT_UPDATE,
  SCHEMA_VALIDATION_ERROR,
 };
